import torch
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "6"
path = '/home/zxw/env/acl/amr-exp/exp-v2/workspace-nmt-big-v2/model/ensemble.pt'
model = torch.load(path, map_location=lambda storage, loc: storage)['model']
for (k, v) in model.items():
    print(k)
"""
encoder.embeddings.make_embedding.word.weight
encoder.embeddings.make_embedding.pe.pe
encoder.transformer.0.self_attn.linear_keys.weight
encoder.transformer.0.self_attn.linear_keys.bias
encoder.transformer.0.self_attn.linear_values.weight
encoder.transformer.0.self_attn.linear_values.bias
encoder.transformer.0.self_attn.linear_query.weight
encoder.transformer.0.self_attn.linear_query.bias
encoder.transformer.0.self_attn.final_linear.weight
encoder.transformer.0.self_attn.final_linear.bias
encoder.transformer.0.feed_forward.w_1.weight
encoder.transformer.0.feed_forward.w_1.bias
encoder.transformer.0.feed_forward.w_2.weight
encoder.transformer.0.feed_forward.w_2.bias
encoder.transformer.0.att_layer_norm.weight
encoder.transformer.0.att_layer_norm.bias
encoder.transformer.0.ffn_layer_norm.weight
encoder.transformer.0.ffn_layer_norm.bias
encoder.transformer.1.self_attn.linear_keys.weight
encoder.transformer.1.self_attn.linear_keys.bias
encoder.transformer.1.self_attn.linear_values.weight
encoder.transformer.1.self_attn.linear_values.bias
encoder.transformer.1.self_attn.linear_query.weight
encoder.transformer.1.self_attn.linear_query.bias
encoder.transformer.1.self_attn.final_linear.weight
encoder.transformer.1.self_attn.final_linear.bias
encoder.transformer.1.feed_forward.w_1.weight
encoder.transformer.1.feed_forward.w_1.bias
encoder.transformer.1.feed_forward.w_2.weight
encoder.transformer.1.feed_forward.w_2.bias
encoder.transformer.1.att_layer_norm.weight
encoder.transformer.1.att_layer_norm.bias
encoder.transformer.1.ffn_layer_norm.weight
encoder.transformer.1.ffn_layer_norm.bias
encoder.transformer.2.self_attn.linear_keys.weight
encoder.transformer.2.self_attn.linear_keys.bias
encoder.transformer.2.self_attn.linear_values.weight
encoder.transformer.2.self_attn.linear_values.bias
encoder.transformer.2.self_attn.linear_query.weight
encoder.transformer.2.self_attn.linear_query.bias
encoder.transformer.2.self_attn.final_linear.weight
encoder.transformer.2.self_attn.final_linear.bias
encoder.transformer.2.feed_forward.w_1.weight
encoder.transformer.2.feed_forward.w_1.bias
encoder.transformer.2.feed_forward.w_2.weight
encoder.transformer.2.feed_forward.w_2.bias
encoder.transformer.2.att_layer_norm.weight
encoder.transformer.2.att_layer_norm.bias
encoder.transformer.2.ffn_layer_norm.weight
encoder.transformer.2.ffn_layer_norm.bias
encoder.transformer.3.self_attn.linear_keys.weight
encoder.transformer.3.self_attn.linear_keys.bias
encoder.transformer.3.self_attn.linear_values.weight
encoder.transformer.3.self_attn.linear_values.bias
encoder.transformer.3.self_attn.linear_query.weight
encoder.transformer.3.self_attn.linear_query.bias
encoder.transformer.3.self_attn.final_linear.weight
encoder.transformer.3.self_attn.final_linear.bias
encoder.transformer.3.feed_forward.w_1.weight
encoder.transformer.3.feed_forward.w_1.bias
encoder.transformer.3.feed_forward.w_2.weight
encoder.transformer.3.feed_forward.w_2.bias
encoder.transformer.3.att_layer_norm.weight
encoder.transformer.3.att_layer_norm.bias
encoder.transformer.3.ffn_layer_norm.weight
encoder.transformer.3.ffn_layer_norm.bias
encoder.transformer.4.self_attn.linear_keys.weight
encoder.transformer.4.self_attn.linear_keys.bias
encoder.transformer.4.self_attn.linear_values.weight
encoder.transformer.4.self_attn.linear_values.bias
encoder.transformer.4.self_attn.linear_query.weight
encoder.transformer.4.self_attn.linear_query.bias
encoder.transformer.4.self_attn.final_linear.weight
encoder.transformer.4.self_attn.final_linear.bias
encoder.transformer.4.feed_forward.w_1.weight
encoder.transformer.4.feed_forward.w_1.bias
encoder.transformer.4.feed_forward.w_2.weight
encoder.transformer.4.feed_forward.w_2.bias
encoder.transformer.4.att_layer_norm.weight
encoder.transformer.4.att_layer_norm.bias
encoder.transformer.4.ffn_layer_norm.weight
encoder.transformer.4.ffn_layer_norm.bias
encoder.transformer.5.self_attn.linear_keys.weight
encoder.transformer.5.self_attn.linear_keys.bias
encoder.transformer.5.self_attn.linear_values.weight
encoder.transformer.5.self_attn.linear_values.bias
encoder.transformer.5.self_attn.linear_query.weight
encoder.transformer.5.self_attn.linear_query.bias
encoder.transformer.5.self_attn.final_linear.weight
encoder.transformer.5.self_attn.final_linear.bias
encoder.transformer.5.feed_forward.w_1.weight
encoder.transformer.5.feed_forward.w_1.bias
encoder.transformer.5.feed_forward.w_2.weight
encoder.transformer.5.feed_forward.w_2.bias
encoder.transformer.5.att_layer_norm.weight
encoder.transformer.5.att_layer_norm.bias
encoder.transformer.5.ffn_layer_norm.weight
encoder.transformer.5.ffn_layer_norm.bias
encoder.layer_norm.weight
encoder.layer_norm.bias
decoder.embeddings.make_embedding.word.weight
decoder.embeddings.make_embedding.pe.pe
decoder.transformer_layers.0.mask
decoder.transformer_layers.0.self_attn.linear_keys.weight
decoder.transformer_layers.0.self_attn.linear_keys.bias
decoder.transformer_layers.0.self_attn.linear_values.weight
decoder.transformer_layers.0.self_attn.linear_values.bias
decoder.transformer_layers.0.self_attn.linear_query.weight
decoder.transformer_layers.0.self_attn.linear_query.bias
decoder.transformer_layers.0.self_attn.final_linear.weight
decoder.transformer_layers.0.self_attn.final_linear.bias
decoder.transformer_layers.0.context_attn.linear_keys.weight
decoder.transformer_layers.0.context_attn.linear_keys.bias
decoder.transformer_layers.0.context_attn.linear_values.weight
decoder.transformer_layers.0.context_attn.linear_values.bias
decoder.transformer_layers.0.context_attn.linear_query.weight
decoder.transformer_layers.0.context_attn.linear_query.bias
decoder.transformer_layers.0.context_attn.final_linear.weight
decoder.transformer_layers.0.context_attn.final_linear.bias
decoder.transformer_layers.0.feed_forward.w_1.weight
decoder.transformer_layers.0.feed_forward.w_1.bias
decoder.transformer_layers.0.feed_forward.w_2.weight
decoder.transformer_layers.0.feed_forward.w_2.bias
decoder.transformer_layers.0.self_att_layer_norm.weight
decoder.transformer_layers.0.self_att_layer_norm.bias
decoder.transformer_layers.0.enc_att_layer_norm.weight
decoder.transformer_layers.0.enc_att_layer_norm.bias
decoder.transformer_layers.0.ffn_layer_norm.weight
decoder.transformer_layers.0.ffn_layer_norm.bias
decoder.transformer_layers.1.mask
decoder.transformer_layers.1.self_attn.linear_keys.weight
decoder.transformer_layers.1.self_attn.linear_keys.bias
decoder.transformer_layers.1.self_attn.linear_values.weight
decoder.transformer_layers.1.self_attn.linear_values.bias
decoder.transformer_layers.1.self_attn.linear_query.weight
decoder.transformer_layers.1.self_attn.linear_query.bias
decoder.transformer_layers.1.self_attn.final_linear.weight
decoder.transformer_layers.1.self_attn.final_linear.bias
decoder.transformer_layers.1.context_attn.linear_keys.weight
decoder.transformer_layers.1.context_attn.linear_keys.bias
decoder.transformer_layers.1.context_attn.linear_values.weight
decoder.transformer_layers.1.context_attn.linear_values.bias
decoder.transformer_layers.1.context_attn.linear_query.weight
decoder.transformer_layers.1.context_attn.linear_query.bias
decoder.transformer_layers.1.context_attn.final_linear.weight
decoder.transformer_layers.1.context_attn.final_linear.bias
decoder.transformer_layers.1.feed_forward.w_1.weight
decoder.transformer_layers.1.feed_forward.w_1.bias
decoder.transformer_layers.1.feed_forward.w_2.weight
decoder.transformer_layers.1.feed_forward.w_2.bias
decoder.transformer_layers.1.self_att_layer_norm.weight
decoder.transformer_layers.1.self_att_layer_norm.bias
decoder.transformer_layers.1.enc_att_layer_norm.weight
decoder.transformer_layers.1.enc_att_layer_norm.bias
decoder.transformer_layers.1.ffn_layer_norm.weight
decoder.transformer_layers.1.ffn_layer_norm.bias
decoder.transformer_layers.2.mask
decoder.transformer_layers.2.self_attn.linear_keys.weight
decoder.transformer_layers.2.self_attn.linear_keys.bias
decoder.transformer_layers.2.self_attn.linear_values.weight
decoder.transformer_layers.2.self_attn.linear_values.bias
decoder.transformer_layers.2.self_attn.linear_query.weight
decoder.transformer_layers.2.self_attn.linear_query.bias
decoder.transformer_layers.2.self_attn.final_linear.weight
decoder.transformer_layers.2.self_attn.final_linear.bias
decoder.transformer_layers.2.context_attn.linear_keys.weight
decoder.transformer_layers.2.context_attn.linear_keys.bias
decoder.transformer_layers.2.context_attn.linear_values.weight
decoder.transformer_layers.2.context_attn.linear_values.bias
decoder.transformer_layers.2.context_attn.linear_query.weight
decoder.transformer_layers.2.context_attn.linear_query.bias
decoder.transformer_layers.2.context_attn.final_linear.weight
decoder.transformer_layers.2.context_attn.final_linear.bias
decoder.transformer_layers.2.feed_forward.w_1.weight
decoder.transformer_layers.2.feed_forward.w_1.bias
decoder.transformer_layers.2.feed_forward.w_2.weight
decoder.transformer_layers.2.feed_forward.w_2.bias
decoder.transformer_layers.2.self_att_layer_norm.weight
decoder.transformer_layers.2.self_att_layer_norm.bias
decoder.transformer_layers.2.enc_att_layer_norm.weight
decoder.transformer_layers.2.enc_att_layer_norm.bias
decoder.transformer_layers.2.ffn_layer_norm.weight
decoder.transformer_layers.2.ffn_layer_norm.bias
decoder.transformer_layers.3.mask
decoder.transformer_layers.3.self_attn.linear_keys.weight
decoder.transformer_layers.3.self_attn.linear_keys.bias
decoder.transformer_layers.3.self_attn.linear_values.weight
decoder.transformer_layers.3.self_attn.linear_values.bias
decoder.transformer_layers.3.self_attn.linear_query.weight
decoder.transformer_layers.3.self_attn.linear_query.bias
decoder.transformer_layers.3.self_attn.final_linear.weight
decoder.transformer_layers.3.self_attn.final_linear.bias
decoder.transformer_layers.3.context_attn.linear_keys.weight
decoder.transformer_layers.3.context_attn.linear_keys.bias
decoder.transformer_layers.3.context_attn.linear_values.weight
decoder.transformer_layers.3.context_attn.linear_values.bias
decoder.transformer_layers.3.context_attn.linear_query.weight
decoder.transformer_layers.3.context_attn.linear_query.bias
decoder.transformer_layers.3.context_attn.final_linear.weight
decoder.transformer_layers.3.context_attn.final_linear.bias
decoder.transformer_layers.3.feed_forward.w_1.weight
decoder.transformer_layers.3.feed_forward.w_1.bias
decoder.transformer_layers.3.feed_forward.w_2.weight
decoder.transformer_layers.3.feed_forward.w_2.bias
decoder.transformer_layers.3.self_att_layer_norm.weight
decoder.transformer_layers.3.self_att_layer_norm.bias
decoder.transformer_layers.3.enc_att_layer_norm.weight
decoder.transformer_layers.3.enc_att_layer_norm.bias
decoder.transformer_layers.3.ffn_layer_norm.weight
decoder.transformer_layers.3.ffn_layer_norm.bias
decoder.transformer_layers.4.mask
decoder.transformer_layers.4.self_attn.linear_keys.weight
decoder.transformer_layers.4.self_attn.linear_keys.bias
decoder.transformer_layers.4.self_attn.linear_values.weight
decoder.transformer_layers.4.self_attn.linear_values.bias
decoder.transformer_layers.4.self_attn.linear_query.weight
decoder.transformer_layers.4.self_attn.linear_query.bias
decoder.transformer_layers.4.self_attn.final_linear.weight
decoder.transformer_layers.4.self_attn.final_linear.bias
decoder.transformer_layers.4.context_attn.linear_keys.weight
decoder.transformer_layers.4.context_attn.linear_keys.bias
decoder.transformer_layers.4.context_attn.linear_values.weight
decoder.transformer_layers.4.context_attn.linear_values.bias
decoder.transformer_layers.4.context_attn.linear_query.weight
decoder.transformer_layers.4.context_attn.linear_query.bias
decoder.transformer_layers.4.context_attn.final_linear.weight
decoder.transformer_layers.4.context_attn.final_linear.bias
decoder.transformer_layers.4.feed_forward.w_1.weight
decoder.transformer_layers.4.feed_forward.w_1.bias
decoder.transformer_layers.4.feed_forward.w_2.weight
decoder.transformer_layers.4.feed_forward.w_2.bias
decoder.transformer_layers.4.self_att_layer_norm.weight
decoder.transformer_layers.4.self_att_layer_norm.bias
decoder.transformer_layers.4.enc_att_layer_norm.weight
decoder.transformer_layers.4.enc_att_layer_norm.bias
decoder.transformer_layers.4.ffn_layer_norm.weight
decoder.transformer_layers.4.ffn_layer_norm.bias
decoder.transformer_layers.5.mask
decoder.transformer_layers.5.self_attn.linear_keys.weight
decoder.transformer_layers.5.self_attn.linear_keys.bias
decoder.transformer_layers.5.self_attn.linear_values.weight
decoder.transformer_layers.5.self_attn.linear_values.bias
decoder.transformer_layers.5.self_attn.linear_query.weight
decoder.transformer_layers.5.self_attn.linear_query.bias
decoder.transformer_layers.5.self_attn.final_linear.weight
decoder.transformer_layers.5.self_attn.final_linear.bias
decoder.transformer_layers.5.context_attn.linear_keys.weight
decoder.transformer_layers.5.context_attn.linear_keys.bias
decoder.transformer_layers.5.context_attn.linear_values.weight
decoder.transformer_layers.5.context_attn.linear_values.bias
decoder.transformer_layers.5.context_attn.linear_query.weight
decoder.transformer_layers.5.context_attn.linear_query.bias
decoder.transformer_layers.5.context_attn.final_linear.weight
decoder.transformer_layers.5.context_attn.final_linear.bias
decoder.transformer_layers.5.feed_forward.w_1.weight
decoder.transformer_layers.5.feed_forward.w_1.bias
decoder.transformer_layers.5.feed_forward.w_2.weight
decoder.transformer_layers.5.feed_forward.w_2.bias
decoder.transformer_layers.5.self_att_layer_norm.weight
decoder.transformer_layers.5.self_att_layer_norm.bias
decoder.transformer_layers.5.enc_att_layer_norm.weight
decoder.transformer_layers.5.enc_att_layer_norm.bias
decoder.transformer_layers.5.ffn_layer_norm.weight
decoder.transformer_layers.5.ffn_layer_norm.bias
decoder.layer_norm.weight
decoder.layer_norm.bias
"""